//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaPresentacion.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CapaPresentacion.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _13183281_1065443036886929_936090605_a {
            get {
                object obj = ResourceManager.GetObject("13183281_1065443036886929_936090605_a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_basura_llena_100 {
            get {
                object obj = ResourceManager.GetObject("icons8_basura_llena_100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_comprobado_48 {
            get {
                object obj = ResourceManager.GetObject("icons8_comprobado_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Imagen_de_WhatsApp_2024_11_11_a_las_15_45_44_ec0335f2 {
            get {
                object obj = ResourceManager.GetObject("Imagen de WhatsApp 2024-11-11 a las 15.45.44_ec0335f2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;body&gt;
        ///    &lt;div style=&quot;width: 80%; margin: auto; background-color: #fff; padding: 30px; border-radius: 8px; 
        ///                box-shadow: 0 0 15px rgba(0, 0, 0, 0.1); font-family: &apos;Arial&apos;, sans-serif; color: #333;&quot;&gt;
        ///        &lt;h1 style=&quot;text-align: center; font-size: 28px; color: #1E88E5; margin-bottom: 10px;&quot;&gt;@nombrenegocio&lt;/h1&gt;
        ///        &lt;p&gt;&lt;strong&gt;RUC:&lt;/strong&gt; @docnegocio&lt;/p&gt;
        ///        &lt;p&gt;&lt;strong&gt;Dirección:&lt;/strong&gt; @direcnegocio&lt;/p&gt;
        ///        &lt;hr style=&quot;border: 0; height: 1px; bac [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string PlantillaCompra {
            get {
                return ResourceManager.GetString("PlantillaCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;body&gt;
        ///    &lt;div style=&quot;width: 80%; margin: auto; background-color: #fff; padding: 30px; border-radius: 8px;
        ///                box-shadow: 0 0 15px rgba(0, 0, 0, 0.1); font-family: &apos;Arial&apos;, sans-serif; color: #333;&quot;&gt;
        ///        
        ///        &lt;h1 style=&quot;text-align: center; font-size: 28px; color: #1E88E5; margin-bottom: 10px;&quot;&gt;@nombrenegocio&lt;/h1&gt;
        ///        &lt;p&gt;&lt;strong&gt;RUC:&lt;/strong&gt; @docnegocio&lt;/p&gt;
        ///        &lt;p&gt;&lt;strong&gt;Dirección:&lt;/strong&gt; @direcnegocio&lt;/p&gt;
        ///        
        ///        &lt;hr style=&quot;border:  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string PlantillaVenta {
            get {
                return ResourceManager.GetString("PlantillaVenta", resourceCulture);
            }
        }
    }
}
